import { useRef, useState } from 'react';
import { X, Download, Loader2 } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { SECTION_LABELS, SECTION_SCHEMAS } from '@/lib/aiDocumentGenerator';
import jsPDF from 'jspdf';

export default function PDFExport({ doc, content, onClose }) {
  const [exporting, setExporting] = useState(false);

  const handleExport = async () => {
    setExporting(true);
    const pdf = new jsPDF({ orientation: 'portrait', unit: 'mm', format: 'a4' });
    const pageWidth = pdf.internal.pageSize.getWidth();
    const margin = 20;
    const contentWidth = pageWidth - margin * 2;
    let y = margin;

    const addPage = () => {
      pdf.addPage();
      y = margin;
    };

    const checkPageBreak = (height) => {
      if (y + height > pdf.internal.pageSize.getHeight() - margin) {
        addPage();
      }
    };

    // Title page
    pdf.setFillColor(37, 99, 235);
    pdf.rect(0, 0, pageWidth, 60, 'F');
    pdf.setTextColor(255, 255, 255);
    pdf.setFontSize(24);
    pdf.setFont('helvetica', 'bold');
    pdf.text(doc.document_type, margin, 30);
    pdf.setFontSize(14);
    pdf.setFont('helvetica', 'normal');
    pdf.text(doc.title || 'Document', margin, 42);
    pdf.setFontSize(10);
    pdf.text(doc.organisation_name || '', margin, 54);

    y = 75;
    pdf.setTextColor(0, 0, 0);

    // Date and metadata
    pdf.setFontSize(9);
    pdf.setTextColor(100, 100, 100);
    pdf.text(`Generated: ${new Date().toLocaleDateString('en-AU', { day: 'numeric', month: 'long', year: 'numeric' })}`, margin, y);
    y += 10;

    // Sections
    const sections = SECTION_SCHEMAS[doc.document_type] || [];
    for (const sectionKey of sections) {
      const sectionContent = content[sectionKey];
      if (!sectionContent) continue;

      const label = SECTION_LABELS[sectionKey] || sectionKey;

      checkPageBreak(20);
      // Section heading
      pdf.setFillColor(240, 245, 255);
      pdf.rect(margin - 3, y - 5, contentWidth + 6, 12, 'F');
      pdf.setFontSize(11);
      pdf.setFont('helvetica', 'bold');
      pdf.setTextColor(37, 99, 235);
      pdf.text(label, margin, y + 3);
      y += 12;

      // Content
      pdf.setFontSize(9.5);
      pdf.setFont('helvetica', 'normal');
      pdf.setTextColor(30, 30, 30);
      const lines = pdf.splitTextToSize(sectionContent, contentWidth);
      for (const line of lines) {
        checkPageBreak(6);
        pdf.text(line, margin, y);
        y += 5.5;
      }
      y += 6;
    }

    // Footer on all pages
    const totalPages = pdf.internal.getNumberOfPages();
    for (let i = 1; i <= totalPages; i++) {
      pdf.setPage(i);
      pdf.setFontSize(8);
      pdf.setTextColor(150, 150, 150);
      pdf.text(`${doc.title} — Page ${i} of ${totalPages}`, margin, pdf.internal.pageSize.getHeight() - 10);
      pdf.text('Generated by TendeX', pageWidth - margin - 30, pdf.internal.pageSize.getHeight() - 10);
    }

    pdf.save(`${doc.title || doc.document_type}-${Date.now()}.pdf`);
    setExporting(false);
    onClose();
  };

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/50 backdrop-blur-sm p-4">
      <div className="bg-card rounded-2xl border border-border shadow-2xl w-full max-w-md p-8">
        <div className="flex items-center justify-between mb-6">
          <h2 className="font-display text-xl font-semibold text-foreground">Export PDF</h2>
          <Button variant="ghost" size="icon" onClick={onClose}><X className="w-4 h-4" /></Button>
        </div>
        <div className="bg-secondary/40 rounded-xl p-4 mb-6 space-y-2 text-sm">
          <div className="flex justify-between">
            <span className="text-muted-foreground">Document type</span>
            <span className="font-medium">{doc.document_type}</span>
          </div>
          <div className="flex justify-between">
            <span className="text-muted-foreground">Title</span>
            <span className="font-medium truncate ml-4">{doc.title}</span>
          </div>
          <div className="flex justify-between">
            <span className="text-muted-foreground">Sections</span>
            <span className="font-medium">{Object.keys(content).length}</span>
          </div>
        </div>
        <p className="text-sm text-muted-foreground mb-6">Your document will be exported as a professional A4 PDF with proper formatting and branding.</p>
        <div className="flex gap-3">
          <Button variant="outline" onClick={onClose} className="flex-1">Cancel</Button>
          <Button onClick={handleExport} disabled={exporting} className="flex-1 gap-2">
            {exporting ? <><Loader2 className="w-4 h-4 animate-spin" />Exporting...</> : <><Download className="w-4 h-4" />Download PDF</>}
          </Button>
        </div>
      </div>
    </div>
  );
}