import { Link } from 'react-router-dom';
import { FileText } from 'lucide-react';

export default function TermsOfService() {
  const sections = [
    {
      title: '1. Acceptance of Terms',
      content: 'By accessing and using TendeX, you agree to be bound by these Terms of Service. If you do not agree with any part of these terms, you may not use the platform. We reserve the right to modify these terms at any time. Your continued use of TendeX constitutes acceptance of the updated terms.'
    },
    {
      title: '2. Description of Service',
      content: 'TendeX is an AI-assisted platform for generating procurement documents including Scope of Work (SOW), Expressions of Interest (EOI), Requests for Quotation (RFQ), and Requests for Proposal (RFP). The generated documents are starting points for your review and should not be relied upon as legal advice. TendeX does not provide legal, financial, or procurement consulting services.'
    },
    {
      title: '3. Account Registration',
      content: 'To use TendeX, you must:\n\n• Be at least 18 years of age\n• Represent a legitimate Australian business entity\n• Provide accurate and complete information during registration\n• Maintain the confidentiality of your login credentials\n• Accept responsibility for all activities under your account\n\nYou must not create accounts for fraudulent purposes or misrepresent your organisation.'
    },
    {
      title: '4. Subscription and Billing',
      content: 'TendeX offers a 14-day free trial allowing creation of 1 procurement document. After the trial period, you must purchase a paid subscription to continue using the platform. Subscriptions are billed monthly or annually via Stripe. Payment information is securely processed by Stripe and not stored by TendeX. You may cancel your subscription at any time, and no refunds are provided for partial months. Refunds for incorrect charges must be requested within 30 days.'
    },
    {
      title: '5. AI-Generated Content Disclaimer',
      content: 'The documents generated by TendeX are AI-assisted starting points created from your input. You acknowledge that:\n\n• You are solely responsible for reviewing, editing, and verifying all generated content before issuing to the market\n• The generated documents may contain inaccuracies, errors, or gaps\n• TendeX does not guarantee legal compliance of generated documents with Commonwealth, state, or local laws\n• TendeX does not provide legal advice, and you should engage a legal professional for compliance review\n• You assume all risk and liability for procurement outcomes and supplier disputes\n\nTendeX is not responsible for any losses, damages, or penalties resulting from the use of generated documents.'
    },
    {
      title: '6. Acceptable Use',
      content: 'You agree not to:\n\n• Use TendeX for fraudulent procurements or deceptive practices\n• Misrepresent your ABN or organisation details\n• Use the platform to create defamatory, illegal, or unethical documents\n• Attempt to access or modify other users\' documents or data\n• Reverse-engineer, scrape, or exploit the platform\n• Use TendeX in violation of any applicable laws\n\nBreach of these terms may result in immediate account termination and legal action.'
    },
    {
      title: '7. Intellectual Property',
      content: 'You retain all intellectual property rights in the procurement content you create. TendeX retains all rights to the platform, its features, documentation, and underlying technology. You grant TendeX a non-exclusive license to use anonymised versions of your documents for AI training and quality improvement purposes only. You may not reproduce, distribute, or commercialise the TendeX platform or any of its features.'
    },
    {
      title: '8. Limitation of Liability',
      content: 'To the maximum extent permitted by law, TendeX and its officers, directors, and employees are not liable for:\n\n• Loss of profits, revenue, data, or anticipated savings\n• Indirect, incidental, or consequential damages\n• Damages arising from the use or inability to use the platform\n• AI-generated content errors or omissions\n• Third-party services (Stripe, AWS, LLM providers)\n\nOur total liability is limited to the amount you paid for your subscription in the last 12 months.'
    },
    {
      title: '9. Governing Law',
      content: 'These Terms of Service are governed by the laws of Western Australia, Australia, without regard to conflict of law principles. You submit to the exclusive jurisdiction of the courts of Western Australia.'
    },
    {
      title: '10. Contact',
      content: 'For questions about these Terms of Service, contact hello@tendex.com.au.\n\nThese Terms of Service were last updated on 14 May 2026.'
    },
  ];

  return (
    <div className="min-h-screen" style={{ backgroundColor: '#080E1A' }}>
      {/* Navigation */}
      <nav className="sticky top-0 z-50 border-b" style={{ borderColor: 'rgba(255,255,255,0.07)', backgroundColor: 'rgba(8,14,26,0.95)', backdropFilter: 'blur(16px)' }}>
        <div className="max-w-4xl mx-auto px-6 h-16 flex items-center">
          <Link to="/" className="flex items-center gap-2 transition-opacity hover:opacity-80">
            <div className="w-8 h-8 bg-[#E53935]/20 rounded-lg flex items-center justify-center border border-[#E53935]/30">
              <FileText className="w-4 h-4 text-[#E53935]" />
            </div>
            <span className="font-syne font-800 text-lg text-white">TendeX</span>
          </Link>
        </div>
      </nav>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-6 py-12">
        <div className="mb-12">
          <h1 className="font-syne font-800 text-4xl md:text-5xl text-white mb-3">Terms of Service</h1>
          <p className="font-dm-sans text-[#8FA5C0]">Effective from 14 May 2026</p>
        </div>

        <div className="space-y-8">
          {sections.map((section, idx) => (
            <section key={idx} className="rounded-xl border border-white/10 p-8" style={{ backgroundColor: 'rgba(255,255,255,0.04)' }}>
              <h2 className="font-syne font-700 text-xl text-white mb-4">{section.title}</h2>
              <p className="font-dm-sans text-[#8FA5C0] leading-relaxed whitespace-pre-line">{section.content}</p>
            </section>
          ))}
        </div>

        {/* Footer */}
        <div className="mt-12 pt-8 border-t" style={{ borderColor: 'rgba(255,255,255,0.07)' }}>
          <p className="font-dm-sans text-sm text-[#5C7A99] text-center">
            For questions about these Terms of Service, contact hello@tendex.com.au
          </p>
        </div>
      </main>
    </div>
  );
}